### PR TITLE
Clarify repository state

### PR DESCRIPTION
**Pull request by NotMyFault**
I'd rather want to keep this repository as an archive, instead of turning it into a general purpose governance repository.
If we want a dedicated governance repository to organize our work, we should create one, but I don't think dumping new content into this one is a great idea.

### CODE REVIEW

**Comment by lemeurherve** [comment]
WDYT of putting back the content currently here in a @jenkins-infra "governance-archive" repository (so infra team can deal with deployment even if there isn't a lot), and keep this repository here for new governance related content, with a link to the archive in its README?

**Comment by NotMyFault** [comment]
> WDYT of putting back the content currently here in a @jenkins-infra "governance-archive" repository (so infra team can deal with deployment even if there isn't a lot), and keep this repository here for new governance related content, with a link to the archive in its README?

`governance-meeting-archive`at the infra org sounds good to me, allows us to start with a fresh repository here, if needed, instead of using the archive longer than needed.

Sorry for the mess :/

**Comment by MarkEWaite** [comment]
> I'd rather want to keep this repository as an archive, instead of turning it into a general purpose governance repository. If we want a dedicated governance repository to organize our work, we should create one, but I don't think dumping new content into this one is a great idea.

I don't understand that concern.  Can you explain further?

The governance board needs a place to store meeting archives that is separate from the Google Docs file that we've used for meeting notes.  Meeting notes from prior to the creation of that Google Docs file have been collected into this repository over the course of the last few weeks (since it was realized that the old archives were no longer available).  Since this is the current archive of meeting notes created before the Google Docs file and we need a place to store the Google Docs content that is independent of Google Docs, why not use this repository?

@uhafner suggested that we could use community.jenkins.io posts for recent meetings, but that does not archive the meeting notes that were created prior to community.jenkins.io.

**Comment by NotMyFault** [comment]
> why not use this repository?

This repository serves old content for mettings.jenkins-ci.org, I don't see why we would want to add new content, that is not served and not intended to be added to meetings.j-ci, to this repository.

> uhafner suggested that we could use community.jenkins.io posts for recent meetings, but that does not archive the meeting notes that were created prior to community.jenkins.io.

We can link from the forums to meetings.j-ci, no?

**Comment by timja** [comment]
> I'd rather want to keep this repository as an archive, instead of turning it into a general purpose governance repository.

Why would we not want to add new meetings here so all meeting content is in one place?

**Comment by dduportal** [comment]
> > why not use this repository?
> 
> This repository serves old content for mettings.jenkins-ci.org, I don't see why we would want to add new content, that is not served and not intended to be added to meetings.j-ci, to this repository.
> 
> > uhafner suggested that we could use community.jenkins.io posts for recent meetings, but that does not archive the meeting notes that were created prior to community.jenkins.io.
> 
> We can link from the forums to meetings.j-ci, no?

About this specific point: There is no issue to serve the content from a branch named `archives` or even better `meetings.jenkins-ci.org`: GH page is used under the hood and is pretty versatile.


But no advise for putting it back as a separate repository: both solutions are imperfect (I got a slight preference around "do not spread information otherwise people get lost" but without strong argument).

**Pull request closed without merging**
